display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/log/php_errors.log

upload_max_filesize = 20M
post_max_size = 25M
max_execution_time = 60
memory_limit = 256M

date.timezone = Europe/Zurich

opcache.enable = 0
